### ISSUE TITLE
Update Oimo modules

### ISSUE THREAD

**Issue by rpaladin** [luboslenco/oimo#2]
Currently, this minor deprecation error is raised when attempting to use Oimo physics.

```
\My_Blend\Libraries\OimoPhysics\Sources/oimo/m/M.hx:40: characters 9-17 : Warning : This typedef is deprecated in favor of js.lib.Error
```

It was [fixed](https://github.com/saharan/OimoPhysics/commit/87c6632b02d59874c3ff998dad24d9c5efcabfe5#diff-a3d0b2b51cfd4558e251caeebcda01d75468ee5bc891166de12c4523c753a971) back in 2020, but wasn't updated in this repository. It may be time to pull changes from the repository again, for all changed files.

**Comment by luboslenco** [comment]
Putting this into archive state, please use the https://github.com/saharan/OimoPhysics repo directly.
